theme: jekyll-theme-minimal
title: Faux Flora Creations
author: Kim Ruebenson
email: fauxfloracreations@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I would love to make flowers for your special someone or event. Send me an email and let's talk!

# social links
github_username:  krueb68 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
